#!/usr/bin/env python
import random, sys, base64, utils
import onetimepass as otp

def random_base32(length=16, random=random.SystemRandom(), chars=base64._b32alphabet.values()):
	return ''.join( 
		random.choice(chars)
		for i in xrange(length)
	)

lot = []

for x in range(1000):
	lot.append(random_base32())

while True:
	mySecret = random.choice(lot)

	myToken = otp.get_totp(mySecret, token_length=6)

	if otp.valid_totp(token = myToken, secret = mySecret, token_length=6):
		break

print mySecret
exit(0)

