#!/usr/bin/env python
import onetimepass as otp

def allow():
	print "allowed"

def deny():
	print "denied by both"

sec = raw_input("Secret:")

tok = raw_input("Token:")

if otp.valid_totp(token=tok, secret=sec, token_length=8):
	allow()

if accept == 0:
	deny()
