#!/usr/bin/env python
from subprocess import call
import onetimepass as otp

def allow():
	call(["clear"])
	print 'accepted'
	# run bash/zsh
	call(["exec","-l","$SHELL"],shell=true)
	exit(0)

def deny():
	call(["clear"])
	print 'denied'
	exit(1)

try:
	# secret key
	sec = "" # enter your key here
	# ask
	tok = raw_input('::')
	# check validity
	if otp.valid_totp(token=tok, secret=sec, token_length=8):
		allow()
	else:
		deny()
except Exception,e:
	# any exception deny
	print(e)
	deny()

# default deny
deny()