#!/usr/bin/env python
from subprocess import call, Popen, PIPE, STDOUT
import onetimepass as otp

def clear():
	Popen(["clear"])

def allow():
	clear()
	print 'accepted'
	# run bash/zsh
	Popen(["/bin/bash"], shell=True) # change default script if wished
	# exit with true
	exit(0)

def deny():
	clear()
	print 'denied'
	# exit with error
	exit(1)

try:
	# check what user
	whoami = Popen(["whoami"], stdout=PIPE, stderr=PIPE)
	username = whoami.stdout.read().split("\n")[0]
	# secret key
	secretdb = {"username":["secret"]} # format = "username":["secretkey"], "username1":["secret1", "secret2"]
	# check validity
	if otp.valid_totp(token=raw_input('~>'), secret=secretdb[username], token_length=8):
		allow()
	else:
		deny()
except KeyboardInterrupt:
	# prevent user keyboard interrupt reporting debug data.
        clear()
	deny()
except Exception,e:
	clear()
	# any exception deny
	print(e)
	deny()

# default deny
deny()
